# config file for testing
# filename should be application.yml

app:
  project: examples
  name: demo
  profiles:
    include:
    - actuator
    - locale
    - logging
    - gorm
    - redis

logging:
  level: info

